"""
Build a standalone Coldbrew "open road" track — world lua + spline, from scratch.

Nothing is copied from a stock world's config. The world is the minimum the engine
needs to render a road under sky: a light, fog-as-sky backdrop, path width, and our
spline (the road ribbon is drawn procedurally along the spline). No baked terrain,
buildings, or .pak — so there's nothing to clip through; it's a clean open road.

Usage:
  python3 -m tracks.build                          # 30 km, flat + 1% grade
  python3 -m tracks.build --length-m 20000 --grade-pct 1.5 --name Coldbrew_OpenRoad_01

Writes payload/worlds/<name>/{<name>.lua, EF_SplinePath_<name>.txt}.
Deploy: scp both to the bike's ME_Assets/Worlds/<name>/, add a LoadRouteFile line.
"""
from __future__ import annotations

import argparse
import os
import uuid

from . import flat, spline

PAYLOAD_DIR = os.path.join(os.path.dirname(__file__), "..", "payload", "worlds")
GUID_NS = uuid.uuid5(uuid.NAMESPACE_URL, "coldbrew:expresso-hd:tracks")
LEVEL_TYPE = "LEVEL_TYPE_BASIC_A"

# Placeholder menu thumbnail — cosmetic only, not used during the ride. A loose
# stock .dds (no .pak needed to load it). Swap for custom art later.
PLACEHOLDER_BROCHURE = "ME_Assets/Worlds/CityExpress/rb_cityexpress.dds"

LUA_TEMPLATE = """\
-------------------------------------------------------------------------------------
-- Coldbrew standalone track: {display_name}
-- Generated by coldbrew/tracks/build.py — built from scratch, no stock-world reuse.
-- Flat-feel open road: gentle weave (keeps the camera frame defined), steady grade,
-- no baked scenery (fog = sky backdrop, road ribbon drawn from the spline).
-------------------------------------------------------------------------------------

Include("GlobalFunctions.lua");

function OnLevelLoad()
    HUD_SetMode(HUD_MODE_ROUTE);

    light = GetGlobalLight();
    SetTranslation(light, CreateF32_vector3(0.0, 6000.0, 0.0));
    SetLightColor(light, CreateF32_vector3(1.0, 1.0, 1.0));
    SetLightIntensity(light, 1.2);

    SetPathWidth({path_width})
    AISetLODDistances(0, 0, 20, 50);

    -- No baked world: fog colour IS the backdrop, so the road reads as an open
    -- road under a clear sky instead of a black void.
    FogSetColor(.62, .76, .92);
    FogSetStartEnd(700, 5500);

    return 101
end

function LevelShellData()
    SetLevelGUID("{guid}")
    SetLevelType({level_type})
    SetLevelAvailability(LEVEL_AVAILABILITY_ALL)
    SetLevelLengthMeters({length_meters:.2f})
    SetLevelExpectedTime("{expected_time}")
    SetLevelPacerPower({pacer_power})
    SetLevelName("{display_name}")
    SetLevelDisplayName("{display_name_upper}")
    SetLeveLSplineFile("ME_Assets/Worlds/{world_dir}/{spline_file}")
    SetStartline(NULL, {start_x:.3f}, {start_y:.3f}, {start_z:.3f}, 238)
    SetFinishline(NULL, {finish_x:.3f}, {finish_y:.3f}, {finish_z:.3f}, 238)
    SetLevelBrochureFile("{brochure}")
    return
end
"""


def _expected_time(length_m: float, pacer_power: int) -> str:
    speed_kph = 20 + (pacer_power - 100) * 0.08
    minutes = (length_m / 1000.0) / speed_kph * 60
    lo = max(5, int(minutes * 0.8 / 5) * 5)
    hi = int(minutes * 1.2 / 5 + 1) * 5
    return f"{lo}-{hi}"


def write_world(world_dir: str, spline_obj: spline.Spline, *,
                display_name: str, path_width: float, pacer_power: int = 110) -> str:
    out_dir = os.path.join(PAYLOAD_DIR, world_dir)
    os.makedirs(out_dir, exist_ok=True)

    spline_filename = f"EF_SplinePath_{world_dir}.txt"
    spline.write(spline_obj, os.path.join(out_dir, spline_filename))

    start, finish = spline_obj.points[0], spline_obj.points[-1]
    length_m = spline_obj.path_length_meters()

    lua = LUA_TEMPLATE.format(
        display_name=display_name,
        display_name_upper=display_name.upper(),
        guid=str(uuid.uuid5(GUID_NS, world_dir)).upper(),
        level_type=LEVEL_TYPE,
        length_meters=length_m,
        expected_time=_expected_time(length_m, pacer_power),
        pacer_power=pacer_power,
        path_width=path_width,
        world_dir=world_dir,
        spline_file=spline_filename,
        start_x=start[0], start_y=start[1], start_z=start[2],
        finish_x=finish[0], finish_y=finish[1], finish_z=finish[2],
        brochure=PLACEHOLDER_BROCHURE,
    )
    with open(os.path.join(out_dir, f"{world_dir}.lua"), "w") as f:
        f.write(lua)

    print(f"  Written {world_dir}/  ({len(spline_obj.points)} pts, {length_m:.0f} m, "
          f"grade≈{(finish[1]-start[1])/ (length_m/0.98) *100:.1f}%, path_width={path_width})")
    return out_dir


def main() -> None:
    ap = argparse.ArgumentParser(description="Build a standalone Coldbrew open-road track")
    ap.add_argument("--name", default="Coldbrew_OpenRoad_01")
    ap.add_argument("--display-name", default="Cold Brew Open Road")
    ap.add_argument("--length-m", type=float, default=30000.0)
    ap.add_argument("--grade-pct", type=float, default=1.0,
                    help="steady grade → steady mild resistance")
    ap.add_argument("--path-width", type=float, default=12.0)
    args = ap.parse_args()

    os.makedirs(PAYLOAD_DIR, exist_ok=True)
    s = flat.generate(length_m=args.length_m, grade_pct=args.grade_pct)
    write_world(args.name, s, display_name=args.display_name, path_width=args.path_width)
    print("\nDeploy: scp the world dir to bike2:.../ME_Assets/Worlds/ + add a LoadRouteFile line.")


if __name__ == "__main__":
    main()
