-------------------------------------------------------------------------------------
-- Coldbrew standalone track: Cold Brew Open Road
-- Generated by coldbrew/tracks/build.py — built from scratch, no stock-world reuse.
-- Flat-feel open road: gentle weave (keeps the camera frame defined), steady grade,
-- no baked scenery (fog = sky backdrop, road ribbon drawn from the spline).
-------------------------------------------------------------------------------------

Include("GlobalFunctions.lua");

function OnLevelLoad()
    HUD_SetMode(HUD_MODE_ROUTE);

    light = GetGlobalLight();
    SetTranslation(light, CreateF32_vector3(0.0, 6000.0, 0.0));
    SetLightColor(light, CreateF32_vector3(1.0, 1.0, 1.0));
    SetLightIntensity(light, 1.2);

    SetPathWidth(12.0)
    AISetLODDistances(0, 0, 20, 50);

    -- No baked world: fog colour IS the backdrop, so the road reads as an open
    -- road under a clear sky instead of a black void.
    FogSetColor(.62, .76, .92);
    FogSetStartEnd(700, 5500);

    return 101
end

function LevelShellData()
    SetLevelGUID("D8CA1197-6E5E-53F1-A973-01461146800D")
    SetLevelType(LEVEL_TYPE_BASIC_A)
    SetLevelAvailability(LEVEL_AVAILABILITY_ALL)
    SetLevelLengthMeters(30001.50)
    SetLevelExpectedTime("65-105")
    SetLevelPacerPower(110)
    SetLevelName("Cold Brew Open Road")
    SetLevelDisplayName("COLD BREW OPEN ROAD")
    SetLeveLSplineFile("ME_Assets/Worlds/Coldbrew_OpenRoad_01/EF_SplinePath_Coldbrew_OpenRoad_01.txt")
    SetStartline(NULL, 1299.440, 748.070, -4474.280, 238)
    SetFinishline(NULL, 28393.932, 1054.192, 9450.398, 238)
    SetLevelBrochureFile("ME_Assets/Worlds/CityExpress/rb_cityexpress.dds")
    return
end
