-------------------------------------------------------------------------------------
-- Coldbrew custom track: Cold Brew Flat
-- Generated by coldbrew/tracks/build.py — do not edit by hand
-- Flat, straight, turn-free. Reuses CityExpress scenery; rides our own spline.
-------------------------------------------------------------------------------------

Include("GlobalFunctions.lua");

function OnLevelLoad()
    HUD_SetMode(HUD_MODE_ROUTE);

    PreloadPackfile("ME_Assets/Worlds/CityExpress/CityExpress.pak");

    light = GetGlobalLight();
    position = CreateF32_vector3(5306.554, 6182.00, -10186.92);
    SetTranslation(light, position);
    color = CreateF32_vector3(1.0, 1.0, 1.0);
    SetLightColor(light, color);
    SetLightIntensity(light, 1.2);
    SetPathWidth(12.0)
    AISetLODDistances(0, 0, 20, 50);
    FogSetColor(.16, .20, .24);
    FogSetStartEnd(200, 1000);

    AddMEngineTerrain("ME_Assets/Worlds/CityExpress/EF_GuardRails_CityExpress.bin")
    AddMEngineTerrain("ME_Assets/Worlds/CityExpress/EF_PlacedObjects_CityExpress.bin")
    AddMEngineTerrain("ME_Assets/Worlds/CityExpress/EF_World_CityExpress.bin")
    skydome = AddMEngineTerrain("ME_Assets/Worlds/CityExpress/EF_Skydome_CityExpress.bin")
    FogDisable(skydome);

    terrain = AddMEngineTerrain("ME_Assets/Worlds/CityExpress/EF_Road_CityExpress.bin")
    octree = GenerateOctree(terrain);
    SetWorldOctree(octree);

    finishLine = AddMEngineTerrain("ME_Assets/Worlds/CityExpress/EF_finishLine_CityExpress.bin")
    SetFinishline(finishLine, 1299.440, 748.070, -1449.070, 0)

    if IsMetricEnabled() then
        marker_km_obj = AddMEngineTerrain("ME_Assets/Worlds/CityExpress/EF_kmMarkers_CityExpress.bin");
        SetName(marker_km_obj, "marker_km");
    else
        marker_mi_obj = AddMEngineTerrain("ME_Assets/Worlds/CityExpress/EF_MileMarkers_CityExpress.bin");
        SetName(marker_mi_obj, "marker_mi");
    end

    LoadSpeedTreeSTF("ME_Assets/Worlds/CityExpress/SpeedTree/CityExpress.stf");

    return 101
end

function LevelShellData()
    SetLevelGUID("F556EB78-3B8F-5286-B513-8CE60D6EA3F3")
    SetLevelType(LEVEL_TYPE_BASIC_A)
    SetLevelAvailability(LEVEL_AVAILABILITY_ALL)
    SetLevelLengthMeters(9092.16)
    SetLevelExpectedTime("20-35")
    SetLevelPacerPower(110)
    SetLevelName("Cold Brew Flat")
    SetLevelDisplayName("COLD BREW FLAT")
    SetLeveLSplineFile("ME_Assets/Worlds/Coldbrew_Flat_01/EF_SplinePath_Coldbrew_Flat_01.txt")
    SetStartline(NULL, 1299.440, 748.070, -4474.280, 0)
    SetFinishline(NULL, 1299.440, 748.070, -1449.070, 0)

    SetLevelBrochureFile("ME_Assets/Worlds/CityExpress/rb_cityexpress.dds")
    SetLevelElevationOverlay("ME_Assets/Worlds/CityExpress/textures/hud_overlay_cityexpress.dds")
    return
end
